var constants = {
    pageNotFoundUrl: "/error/404",
    currentYear: (new Date().getFullYear()),
    totalOnPage: 40,
    subAliasArr: ["phu-de", "thuyet-minh", "long-tieng", "da-hoan-thanh", "moi-cap-nhat",
        "thai-lan", "trung-quoc", "nhat-ban", "my", "dai-loan", "hong-kong", "han-quoc", "an-do", "phap", "anh", "khac",
        "tam-ly", "kinh-di", "vien-tuong", "hanh-dong", "hai-huoc", "vo-thuat", "co-trang", "than-thoai", "hoat-hinh", "phieu-luu", "chieu-rap", "hinh-su", "tv-show", "chien-tranh", "am-nhac", "anime", "khoa-hoc-tai-lieu"],
    subAliasMap: {
        "phim-le": "Phim lẻ",
        "phim-bo": "Phim Bộ",
        "phu-de": "Phụ Đề",
        "thuyet-minh": "Thuyết Minh",
        "long-tieng": "Lồng Tiếng",
        "phim-phu-de": "Phim Phụ Đề",
        "phim-thuyet-minh": "Phim Thuyết Minh",
        "phim-long-tieng": "Phim Lồng Tiếng",
        "thai-lan": "Thái Lan",
        "trung-quoc": "Trung Quốc",
        "nhat-ban": "Nhật Bản",
        "my": "Mỹ",
        "dai-loan": "Đài Loan",
        "hong-kong": "Hồng Kông",
        "han-quoc": "Hàn Quốc",
        "an-do": "Ấn Độ",
        "phap": "Pháp",
        "anh": "Anh",
        "khac": "Khác",
        "phim-thai-lan": "Phim Thái Lan",
        "phim-trung-quoc": "Phim Trung Quốc",
        "phim-nhat-ban": "Phim Nhật Bản",
        "phim-my": "Phim Mỹ",
        "phim-dai-loan": "Phim Đài Loan",
        "phim-hong-kong": "Phim Hồng Kông",
        "phim-han-quoc": "Phim Hàn Quốc",
        "phim-an-do": "Phim Ấn Độ",
        "phim-phap": "Phim Pháp",
        "phim-anh": "Phim Anh",
        "phim-khac": "Đang cập nhật",
        "phim-tv-show": "TV Show",
        "phim-tam-ly": "Phim Tâm lý",
        "phim-kinh-di": "Phim Kinh Dị",
        "phim-vien-tuong": "Phim Viễn Tưởng",
        "phim-hanh-dong": "Phim Hành Dộng",
        "phim-hai-huoc": "Phim Hài Hước",
        "phim-vo-thuat": "Phim Võ Thuật",
        "phim-co-trang": "Phim Cổ trang",
        "phim-than-thoai": "Phim Thần Thoại",
        "phim-hoat-hinh": "Phim Hoạt Hình",
        "phim-phieu-luu": "Phim Phiêu Lưu",
        "phim-chieu-rap": "Phim Chiếu Rạp",
        "phim-hinh-su": "Phim Hình Sự",
        "phim-chien-tranh": "Phim Chiến Tranh",
        "phim-am-nhac": "Phim Âm Nhạc",
        "phim-anime": "Phim Anime",
        "phim-khoa-hoc-tai-lieu": "Khoa Học Tài Liệu"}
};

module.exports = constants;
